apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: nikitamathe/api-gateway:latest
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/banking?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: AUTH_SERVICE_HOST
              value: "auth-service"
            - name: AUTH_SERVICE_PORT
              value: "8081"
            - name: ACCOUNT_SERVICE_HOST
              value: "account-service"
            - name: ACCOUNT_SERVICE_PORT
              value: "8082"
            - name: TRANSACTION_SERVICE_HOST
              value: "transaction-service"
            - name: TRANSACTION_SERVICE_PORT
              value: "8083"
            - name: NOTIFICATION_SERVICE_HOST
              value: "notification-service"
            - name: NOTIFICATION_SERVICE_PORT
              value: "8084"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user-password
          volumeMounts:
            - name: gateway-config
              mountPath: /app/config/application.yml
              subPath: application.yml
      volumes:
        - name: gateway-config
          configMap:
            name: api-gateway-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: banking
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8085
      targetPort: 8085
