apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: banking
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secret
  namespace: banking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: mysql-root-password
      remoteRef:
        key: banking/mysql-secret
        property: mysql-root-password
    - secretKey: mysql-user
      remoteRef:
        key: banking/mysql-secret
        property: mysql-user
    - secretKey: mysql-user-password
      remoteRef:
        key: banking/mysql-secret
        property: mysql-user-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jwt-secret
  namespace: banking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: jwt-secret
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: banking/jwt-secret
        property: jwt-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secret
  namespace: banking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: grafana-secret
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: admin-user
      remoteRef:
        key: banking/grafana-secret
        property: admin-user
    - secretKey: admin-password
      remoteRef:
        key: banking/grafana-secret
        property: admin-password