apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: banking
type: Opaque
data:
  jwt-secret: NTVhNmNiOWY0MDM3ZjVkZmVjNGZlZmIxMGMyODdlOTlmNzcwMzA4MjczZGFlMGE0ODU3Y2MxNmIyZTQxZmZmNg==
