apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: banking

resources:
  - namespace.yaml
  - mysql-secret.yaml
  - jwt-secret.yaml
  - grafana-secret.yaml
  - alertmanager-config.yaml
  - alertmanager-deployment.yaml
  - loki-deployment.yaml
  - promtail-daemonset.yaml
  - mysql-statefulset.yaml
  - redis-deployment.yaml
  - account-deployment.yaml
  - auth-deployment.yaml
  - transaction-deployment.yaml
  - notification-deployment.yaml
  - api-gateway-deployment.yaml
  - api-gateway-config.yaml
  - frontend-deployment.yaml
  - frontend-nginx-config.yaml
  - observability.yaml
  - network-policies.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - resource-quotas.yaml

images:
  - name: 340529311540.dkr.ecr.us-east-1.amazonaws.com/account-service
    newTag: latest
  - name: 340529311540.dkr.ecr.us-east-1.amazonaws.com/auth-service
    newTag: latest
  - name: 340529311540.dkr.ecr.us-east-1.amazonaws.com/transaction-service
    newTag: latest
  - name: 340529311540.dkr.ecr.us-east-1.amazonaws.com/notification-service
    newTag: latest
  - name: 340529311540.dkr.ecr.us-east-1.amazonaws.com/api-gateway
    newTag: latest
  - name: 340529311540.dkr.ecr.us-east-1.amazonaws.com/frontend
    newTag: latest
