apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: nikitamathe/notification-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/banking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user-password
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: banking
spec:
  selector:
    app: notification-service
  ports:
    - port: 8080
      targetPort: 8084
